$.extend(Tag.actions.trans.rules,{zoom_out_to:{type:"FLOAT"},zoom_in_from:{type:"FLOAT"},zoom_in_draw_count:{type:"INT"}});
Tag.actions.trans.methods.zoom=new TransMethod({prepare:function(b){this.beginning=Date.now();this.tempCanvas=document.createElement("canvas");this.tempCanvas.width=config.scWidth;this.tempCanvas.height=config.scHeight;this.tempContext=this.tempCanvas.getContext("2d");this.zoomOutTo=0.5;this.zoomInFrom=1.5;this.drawCount=10;"zoom_out_to"in b&&(this.zoomOutTo=b.zoom_out_to);"zoom_in_from"in b&&(this.zoomInFrom=b.zoom_in_from);"zoom_in_draw_count"in b&&(this.drawCount=b.zoom_in_draw_count)},transit:function(b,
e,c,a){b=(Date.now()-this.beginning)/b.time;1<b&&(b=1);a=a.getContext("2d");for(var d=this.drawCount,g=1-(1-this.zoomOutTo)*b,h=0;h<d;h++){var k=h/(d-1),f=1-(1-g)*k,l=e.width*f,f=e.height*f,m=(e.width-l)/2,n=(e.height-f)/2;a.globalAlpha=1-k;a.drawImage(e,0,0,e.width,e.height,m,n,l,f)}this.tempContext.clearRect(0,0,this.tempCanvas.width,this.tempCanvas.height);e=this.zoomInFrom-(this.zoomInFrom-1)*b;for(h=0;h<d;h++)k=h/(d-1),f=1+(e-1)*k,l=c.width*f,f*=c.height,m=(c.width-l)/2,n=(c.height-f)/2,this.tempContext.globalAlpha=
1-k,this.tempContext.drawImage(c,0,0,c.width,c.height,m,n,l,f);a.save();a.globalAlpha=b;a.drawImage(this.tempCanvas,0,0,this.tempCanvas.width,this.tempCanvas.height);a.restore()},teardown:function(){delete this.beginning;delete this.tempCanvas;delete this.zoomOutTo;delete this.zoomInFrom;delete this.drawCount}});
Tag.actions.trans.methods.fadethrough=new TransMethod({canRun:function(){return supportCssProperty(["animationName","animationDuration"])},transitAllLayers:function(b,e,c,a){this.cssTag=document.createElement("style");this.cssTag.type="text/css";a="@-webkit-keyframes fadethrough {0% { -webkit-transform: scale(1) translate(0,0);opacity: 1;} 100% { -webkit-transform: scale(1.5) translate(0,-40px); opacity: 0; }};";a+=a.replace(/-webkit-/g,"-moz-")+a.replace(/-webkit-/g,"-o-")+a.replace(/-webkit-/g,
"");a=document.createTextNode(a);this.cssTag.appendChild(a);document.getElementsByTagName("head")[0].appendChild(this.cssTag);$(c).css({"animation-duration":b.time+"ms","animation-timing-function":"ease-in-out","animation-fill-mode":"both","animation-name":"fadethrough","z-index":"2"});$(e).css("z-index","1")},teardownAllLayers:function(b,e,c,a){document.getElementsByTagName("head")[0].removeChild(this.cssTag);$(c).css({"animation-duration":"","animation-timing-function":"","animation-fill-mode":"",
"animation-name":"","z-index":""});$(e).css("z-index","");delete this.cssTag}});
Tag.actions.trans.methods.multiflip=new TransMethod({canRun:function(){return supportCssProperty(["animationName","perspective"])},transitAllLayers:function(b,e,c,a){this.cssTag=document.createElement("style");this.cssTag.type="text/css";var d="@-webkit-keyframes flip-out { \n0% { \n-webkit-transform:rotateX(0deg); \n} 100% { \n-webkit-transform:rotateX(90deg) \n}} \n@-webkit-keyframes flip-in { \n0% { -webkit-transform:rotateX(-90deg); m} 100% { \n-webkit-transform:rotateX(0deg); \n} \n} ",d=d+(d.replace(/-webkit-/g,
"-moz-")+d.replace(/-webkit-/g,"-o-")+d.replace(/-webkit-/g,"")),d=document.createTextNode(d);this.cssTag.appendChild(d);document.getElementsByTagName("head")[0].appendChild(this.cssTag);$(c).css({display:"none"});$(e).css({display:"none"});$(a).css("perspective","1000px");var g=Math.round(c.width/10),h=b.time/1.72,k=0.08*h;this.foreCanvases=[];this.backCanvases=[];for(b=0;10>b;b++){var d=document.createElement("canvas"),f=document.createElement("canvas");d.height=f.height=c.height;d.width=f.width=
c.width/10;$([d,f]).css({position:"absolute",left:g*b+"px",top:"0","animation-duration":h/2+"ms","animation-fill-mode":"both"}).appendTo(a);$(d).css({"animation-name":"flip-out","animation-delay":b*k+"ms","animation-timing-function":"ease-in"});$(f).css({"animation-name":"flip-in","animation-delay":b*k+h/2+"ms","animation-timing-function":"ease-out"});this.foreCanvases.push(d);this.backCanvases.push(f)}var l=Date.now(),m=this;this.syncCanvases=function(a){for(var b=0;b<m.foreCanvases.length;b++){var d=
Date.now()-l,f=m.foreCanvases[b],p=m.backCanvases[b];(d<b*k+h/2||!0===a)&&f.getContext("2d").drawImage(c,g*b,0,g,c.height,0,0,g,c.height);(d>=b*k+h/2||!0===a)&&p.getContext("2d").drawImage(e,g*b,0,g,e.height,0,0,g,e.height)}};$([c,e]).on("draw",this.syncCanvases);this.syncCanvases(!0)},teardownAllLayers:function(b,e,c,a){$([c,e]).off("draw",this.syncCanvases);document.getElementsByTagName("head")[0].removeChild(this.cssTag);delete this.cssTag;$(c).css({display:"block"});$(e).css({display:"block"});
$(a).css("perspective","");for(b=0;b<this.foreCanvases;b++)$([this.foreCanvases[b],this.backCanvases[b]]).remove();delete this.foreCanvases;delete this.backCanvases;delete this.syncCanvases}});
Tag.actions.trans.methods.cube=new TransMethod({canRun:function(){return browser.isIE?!1:supportCssProperty(["animationName","perspective"])},transitAllLayers:function(b,e,c,a){this.cssTag=document.createElement("style");this.cssTag.type="text/css";var d="@-webkit-keyframes cube-up {0%{ -webkit-transform:rotateX(0deg) translateZ(0);}100%{-webkit-transform:rotateX(90deg) translateZ("+config.scHeight+"px);}};",d=d+(d.replace(/-webkit-/g,"-moz-")+d.replace(/-webkit-/g,"-o-")+d.replace(/-webkit-/g,"")),
d=document.createTextNode(d);this.cssTag.appendChild(d);document.getElementsByTagName("head")[0].appendChild(this.cssTag);this.rotateDiv=document.createElement("div");$(e).css({"transform-origin":"50% 0 0",transform:"rotateX(-90deg) translateZ("+config.scHeight+"px)"});$(c).css({"transform-origin":"50% 0 0"});$(a).css({width:$(a).width()+"px",height:$(a).height()+"px",perspective:"1000px","transform-style":"preserve-3d","transform-origin":"50% 0"}).append(this.rotateDiv);$(this.rotateDiv).css({width:$(a).width()+
"px",height:$(a).height()+"px","transform-origin":"50% 100%","transform-style":"preserve-3d","animation-duration":b.time+"ms","animation-timing-function":"ease-in-out","animation-fill-mode":"both","animation-name":"cube-up"}).append(e).append(c)},teardownAllLayers:function(b,e,c,a){document.getElementsByTagName("head")[0].removeChild(this.cssTag);delete this.cssTag;$(e).css({"transform-origin":"",transform:""});$(c).css({"transform-origin":""});$(a).append(c).append(e);$(this.rotateDiv).remove();
delete this.rotateDiv}});Tag.actions.trans.methods.blindup=new TransMethod({prepare:function(b){this.beginning=Date.now()},transit:function(b,e,c,a){var d=a.getContext("2d");d.clearRect(0,0,a.width,a.height);a=(Date.now()-this.beginning)/b.time;1<a&&(a=1);b=c.height/10;a=b*(1-a);d.drawImage(c,0,0,c.width,c.height);for(c=0;10>c;c++){var g=b*c;0<a&&d.drawImage(e,0,g,e.width,a,0,g,e.width,a)}},teardown:function(){delete this.beginning}});
Tag.actions.trans.methods.blinddown=new TransMethod({prepare:function(b){this.beginning=Date.now()},transit:function(b,e,c,a){var d=a.getContext("2d");d.clearRect(0,0,a.width,a.height);a=(Date.now()-this.beginning)/b.time;1<a&&(a=1);b=c.height/10;a*=b;d.drawImage(e,0,0,e.width,e.height);for(e=0;10>e;e++){var g=b*e;0<a&&d.drawImage(c,0,g,c.width,a,0,g,c.width,a)}},teardown:function(){delete this.beginning}});
Tag.actions.trans.methods.toss=new TransMethod({canRun:function(){return supportCssProperty(["animationName","animationDuration"])},transitAllLayers:function(b,e,c,a){this.cssTag=document.createElement("style");this.cssTag.type="text/css";c="@-webkit-keyframes toss {0% { -webkit-transform: rotate(-30deg) scale(1.3) translate(-20px,-250px); opacity: 0; } 100% { transform: scale(1) translate(0,0) rotate(0deg); opacity: 1; }};";c+=c.replace(/-webkit-/g,"-moz-")+c.replace(/-webkit-/g,"-o-")+c.replace(/-webkit-/g,
"");c=document.createTextNode(c);this.cssTag.appendChild(c);document.getElementsByTagName("head")[0].appendChild(this.cssTag);$(e).css({"animation-duration":b.time+"ms","animation-timing-function":"ease-in-out","animation-fill-mode":"both","animation-name":"toss"})},teardownAllLayers:function(b,e,c,a){document.getElementsByTagName("head")[0].removeChild(this.cssTag);$(e).css({"animation-duration":"","animation-timing-function":"","animation-fill-mode":"","animation-name":""});delete this.cssTag}});
Tag.actions.trans.methods.horizontalflip=new TransMethod({canRun:function(){return supportCssProperty(["animationName","animationDuration","animationFillMode","perspective"])},transitAllLayers:function(b,e,c,a){this.cssTag=document.createElement("style");this.cssTag.type="text/css";var d="@-webkit-keyframes flip-in {0%{-webkit-transform:rotateX(-90deg);}100%{-webkit-transform:rotateX(0deg);}} \n@-webkit-keyframes flip-out {0%{-webkit-transform:rotateX(0deg);}100%{-webkit-transform:rotateX(90deg);}};",
d=d+(d.replace(/-webkit-/g,"-moz-")+d.replace(/-webkit-/g,"-o-")+d.replace(/-webkit-/g,"")),d=document.createTextNode(d);this.cssTag.appendChild(d);document.getElementsByTagName("head")[0].appendChild(this.cssTag);$(a).css("perspective","1000px");$(c).css({"animation-duration":b.time/2+"ms","animation-timing-function":"ease-in","animation-fill-mode":"both","animation-name":"flip-out"});$(e).css({"animation-duration":b.time/2+"ms","animation-delay":b.time/2+"ms","animation-timing-function":"ease-out",
"animation-fill-mode":"both","animation-name":"flip-in"})},teardownAllLayers:function(b,e,c,a){document.getElementsByTagName("head")[0].removeChild(this.cssTag);$(a).css("perspective","");$(c).css({"animation-duration":"","animation-timing-function":"","animation-fill-mode":"","animation-name":""});delete this.cssTag}});